/**
 * BlindOracle — Witness definitions and private state
 *
 * Witnesses provide PRIVATE inputs to Compact circuits. The prover
 * (player's browser via Lace wallet) executes them locally; their values
 * NEVER leave the prover — only the ZK proof of correct execution is
 * posted on-chain.
 *
 * Vocabulary reminder:
 *   myAnswer — the number others will try to guess. PRIVATE.
 *   myGuess  — the number the player thinks opponent's answer is. PUBLIC.
 *              (NOT a witness — passed as a plain circuit parameter.)
 */

export interface BlindOraclePrivateState {
  /** The player's local signing key (Bytes<32>). */
  readonly secretKey: Uint8Array;

  /** The number the player is locking in for OTHERS to guess. PRIVATE. */
  readonly myAnswer: number;

  /**
   * Random 32-byte salt mixed into the answer commitment.
   * Freshly generated per-round to prevent commitment-matching attacks
   * when two players pick the same answer.
   *
   * MUST be persisted locally (wallet/localStorage) so the player can
   * reveal their answer at God Window time.
   */
  readonly answerSalt: Uint8Array;
}

export interface BlindOracleWitnessContext {
  readonly privateState: BlindOraclePrivateState;
}

/**
 * Witness implementations for the blind-oracle.compact contract.
 *
 * These are wired to the Compact runtime via the WitnessProvider
 * interface exported by @midnight-ntwrk/compact-runtime. The exact
 * wiring is generated by the compact compiler; this module provides
 * the logic each witness runs.
 */
export const witnesses = {
  /**
   * Returns the player's local signing key. Used by every authorization
   * circuit to derive the caller's public key and verify identity.
   */
  local_secret_key: ({ privateState }: BlindOracleWitnessContext): Uint8Array => {
    return privateState.secretKey;
  },

  /**
   * Returns the player's answer. Used inside circuits that need to
   * reason about the raw value (e.g., could be used in a future
   * self-reveal or proof-of-knowledge circuit). For entry/commit, the
   * commitment is computed off-chain by the UI and passed as a circuit
   * parameter.
   */
  get_my_answer: ({ privateState }: BlindOracleWitnessContext): bigint => {
    return BigInt(privateState.myAnswer);
  },

  /** Returns the salt mixed into the answer commitment. */
  get_answer_salt: ({ privateState }: BlindOracleWitnessContext): Uint8Array => {
    return privateState.answerSalt;
  },
};
